# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repository
        uses: actions/checkout@v2
      
      - name: Install packages
        run: npm install
      
      - name: Compile Typescript
        run: npm run compile
  tests:
    name: "Unit tests"
    runs-on: "ubuntu-latest"
    steps:
      - name: Run unit tests with coverage
        # You may pin to the exact commit or the version.
        # uses: mattallty/jest-github-action@43bbcd073fa43a927322f188220b6592acae003b
        uses: mattallty/jest-github-action@v1.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # The test command to run
          test-command: npm run test:ci
          working-directory: coverage
          # Comment PRs with code coverage
          coverage-comment: true
          # Only run tests on changed files (over base branch)
          changes-only: false